In [2]:
import pickle as pkl
import numpy as np
import pandas as pd

# select an example molecule

In [3]:
df_smi = pd.read_csv('esol.csv')

In [4]:
df_smi

smiles  logSolubility
0                  CNC(=O)Oc1cccc2CC(C)(C)Oc12         -2.800
1                       CNC(=O)Oc1cc(C)cc(C)c1         -2.581
2                           Brc1cc(Br)cc(Br)c1         -5.600
3                     CCC(=O)Nc1ccc(Cl)c(Cl)c1         -3.000
4                               C1CCc2ccccc2C1         -4.370
...                                        ...            ...
1035                             CN(C)c1ccccc1         -1.920
1036                 Nc2cnn(c1ccccc1)c(=O)c2Cl         -2.878
1037                                  CCC(C)Cl         -1.960
1038  CC34CCC1C(CCC2=CC(=O)CCC12O)C3CCC4(O)C#C         -4.570
1039                          Brc1cccc2ccccc12         -4.350

[1040 rows x 2 columns]

In [5]:
df_smi.iloc[[7]]

smiles  logSolubility
7   CC#N           0.26

In [6]:
df_bond_features = pkl.load(open('esol_wb97xd_bond_RBF_features.pkl', 'rb'))

In [7]:
df_bond_features

prop0  \
0     [5.6758025108324885e-05, 2.4019177584504805e-0...   
1     [5.661329724634824e-05, 2.3564010689251515e-07...   
2     [7.637725819772552e-06, 4.05674944218469e-11, ...   
3     [1.1177882599387758e-05, 4.2553852493031154e-0...   
4     [1.791986530932089e-05, 1.6839664031038976e-05...   
...                                                 ...   
1035  [6.49513086375392e-05, 6.49513086375392e-05, 1...   
1036  [6.600073226878128e-08, 5.507966420168615e-07,...   
1037  [1.1116409959162692e-05, 1.801685829079933e-05...   
1038  [2.836807967539645e-05, 5.0063885071765794e-05...   
1039  [1.0203946507554959e-05, 1.5994666164083675e-1...   

                                                  prop1  \
0     [0.0002472987346771834, 1.5315532113709687e-06...   
1     [0.0002467174836964668, 1.504334174437704e-06,...   
2     [3.865591839670033e-05, 4.196273753478917e-10,...   
3     [5.504423077582466e-05, 0.00018961020103439242...   
4     [8.524333159099291e-05, 8.047423394436857e-05,...   
...                                                 ...   
1035  [0.00028001352100238963, 0.0002800135210023896...   
1036  [4.5562305639149854e-07, 3.3314591503207862e-0...   
1037  [5.4763416631026314e-05, 8.56704442276577e-05,...   
1038  [0.00013038147258103813, 0.0002202800940382848...   
1039  [5.058092646830671e-05, 2.15175785687362e-12, ...   

                                                  prop2  \
0     [0.0009556550847726576, 8.661452132878687e-06,...   
1     [0.0009535996137792283, 8.517734411167893e-06,...   
2     [0.00017352121894393212, 3.849763958525944e-09...   
3     [0.00024040789854464894, 0.0007493231941367301...   
4     [0.0003596422873827817, 0.000341086823063407, ...   
...                                                 ...   
1035  [0.0010706678496459172, 0.0010706678496459172,...   
1036  [2.7896344282978857e-06, 1.7871555867924138e-0...   
1037  [0.00023927712314809053, 0.0003612997301610326...   
1038  [0.0005314794633336451, 0.0008596281321848755,...   
1039  [0.0002223770929985187, 2.5674161984601447e-11...   

                                                  prop3  \
0     [0.0032754058300485294, 4.344441875351286e-05,...   
1     [0.003269014660103307, 4.27748533469915e-05, 1...   
2     [0.0006908342265511991, 3.132485390568653e-08,...   
3     [0.0009312586497420794, 0.0026264026923508745,...   
4     [0.0013457542173940466, 0.001282205675556896, ...   
...                                                 ...   
1035  [0.003630907482874837, 0.003630907482874837, 0...   
1036  [1.5148636955355005e-05, 8.503053194083306e-05...   
1037  [0.0009272492349522156, 0.0013514155684602948,...   
1038  [0.0019215060488134586, 0.002975299220667238, ...   
1039  [0.0008671175568553648, 2.7169635910752487e-10...   

                                                  prop4  \
0     [0.009956661045355562, 0.00019326888218757735,...   
1     [0.009939220651525166, 0.00019051870739571436,...   
2     [0.0024393817164934497, 2.2606257397536817e-07...   
3     [0.003199459147076358, 0.008164660227886401, 4...   
4     [0.0044662744838708975, 0.004274990067448376, ...   
...                                                 ...   
1035  [0.010920946171614439, 0.010920946171614439, 0...   
1036  [7.295994252200313e-05, 0.00035881624005485135...   
1037  [0.0031869588142835396, 0.004483269647747515, ...   
1038  [0.006161432375358339, 0.009133460174198704, 0...   
1039  [0.002998821202596652, 2.5500930200255475e-09,...   

                                                  prop5  \
0     [0.026843985146846955, 0.0007625609130801504, ...   
1     [0.02680232432539096, 0.0007526124278904729, 2...   
2     [0.007639595160533492, 1.4469480685576015e-06,...   
3     [0.009749166351872207, 0.022511248380618288, 5...   
4     [0.01314648749524303, 0.012641458617083183, 0....   
...                                                 ...   
1035  [0.029133322213785673, 0.029133322213785673, 0...   
1036  [0.00031165928565952044, 0.

In [8]:
df_bond_features.iloc[[7]]

prop0  \
7  [1.7828619163059985e-06, 8.29661219347401e-53,...   

                                               prop1  \
7  [9.980367280480984e-06, 1.670114159435355e-50,...   

                                               prop2  \
7  [4.955186462742911e-05, 2.9817840534816124e-48...   

                                               prop3  \
7  [0.00021820170587215075, 4.721618347478586e-46...   

                                               prop4  \
7  [0.000852198849728312, 6.631171099809035e-44, ...   

                                               prop5  \
7  [0.0029519459953580214, 8.259889742541822e-42,...   

                                               prop6  \
7  [0.009069023650622864, 9.12521127928867e-40, 0...   

                                               prop7  \
7  [0.024711398435672452, 8.941209466424832e-38, ...   

                                               prop8  \
7  [0.05971985903973473, 7.770237118683399e-36, 0...   

                                               prop9  ...  \
7  [0.12800439667017813, 5.989036184740178e-34, 0...  ...   

                                             prop190  \
7  [1.2664165549094086e-14, 1.2664165549094086e-1...   

                                             prop191  \
7  [2.5062218871452567e-15, 2.5062218871452567e-1...   

                                             prop192  \
7  [4.765304735299122e-16, 4.765304735299122e-16,...   

                                             prop193  \
7  [8.705426622296251e-17, 8.705426622296251e-17,...   

                                             prop194  \
7  [1.5279799682873048e-17, 1.5279799682873048e-1...   

                                             prop195  \
7  [2.576757109154981e-18, 2.576757109154981e-18,...   

                                             prop196  \
7  [4.175010055850514e-19, 4.175010055850514e-19,...   

                                             prop197  \
7  [6.499347972070847e-20, 6.499347972070847e-20,...   

                                             prop198  \
7  [9.72098502030078e-21, 9.72098502030078e-21, 9...   

                                             prop199  
7  [1.396943943147109e-21, 1.396943943147109e-21,...  

[1 rows x 200 columns]

In [9]:
# every 50 prop is a descriptor 
# len of each prop equals to num of atoms or bonds in molecule

In [10]:
df_bond_features.iloc[[7]].prop0.values

array([array([1.78286192e-06, 8.29661219e-53, 2.82640722e-04, 2.82640722e-04,
              2.82640722e-04])                                               ],
      dtype=object)

In [18]:
import csv
import os
import pickle
from typing import List

import numpy as np
import pandas as pd
from rdkit.Chem import PandasTools

def load_valid_atom_or_bond_features(path: str, smiles: List[str]) -> List[np.ndarray]:
    """
    Loads features saved in a variety of formats.

    Supported formats:

    * :code:`.npz` descriptors are saved as 2D array for each molecule in the order of that in the data.csv
    * :code:`.pkl` / :code:`.pckl` / :code:`.pickle` containing a pandas dataframe with smiles as index and numpy array of descriptors as columns
    * :code:'.sdf' containing all mol blocks with descriptors as entries

    :param path: Path to file containing atomwise features.
    :return: A list of 2D array.
    """

    extension = os.path.splitext(path)[1]

    if extension == '.npz':
        container = np.load(path)
        features = [container[key] for key in container]

    elif extension in ['.pkl', '.pckl', '.pickle']:
        features_df = pd.read_pickle(path)
        if features_df.iloc[0, 0].ndim == 1:
            features = features_df.apply(lambda x: np.stack(x.tolist(), axis=1), axis=1).tolist()
        elif features_df.iloc[0, 0].ndim == 2:
            features = features_df.apply(lambda x: np.concatenate(x.tolist(), axis=1), axis=1).tolist()
        else:
            raise ValueError(f'Atom/bond descriptors input {path} format not supported')

    elif extension == '.sdf':
        features_df = PandasTools.LoadSDF(path).drop(['ID', 'ROMol'], axis=1).set_index('SMILES')

        features_df = features_df[~features_df.index.duplicated()]

        # locate atomic descriptors columns
        features_df = features_df.iloc[:, features_df.iloc[0, :].apply(lambda x: isinstance(x, str) and ',' in x).to_list()]
        features_df = features_df.reindex(smiles)
        if features_df.isnull().any().any():
            raise ValueError('Invalid custom atomic descriptors file, Nan found in data')

        features_df = features_df.applymap(lambda x: np.array(x.replace('\r', '').replace('\n', '').split(',')).astype(float))

        features = features_df.apply(lambda x: np.stack(x.tolist(), axis=1), axis=1).tolist()

    else:
        raise ValueError(f'Extension "{extension}" is not supported.')

    return features

In [42]:
# load bond feature
loaded_bond = load_valid_atom_or_bond_features('esol_wb97xd_bond_RBF_features.pkl', df_smi['smiles'].values)

In [47]:
loaded_bond[7].shape

(5, 200)

In [57]:
(mask_features_extra(loaded_bond[7], [True]*4) == loaded_bond[7]).all()

True

In [58]:
(mask_features_extra(loaded_bond[7], [False]*4) == loaded_bond[7]).any()

False

In [21]:
# load and test atom feature 
loaded = load_valid_atom_or_bond_features('esol_wb97xd_atom_RBF_features.pkl', df_smi['smiles'].values)

In [22]:
loaded[0]

array([[1.15083505e-007, 1.15745395e-006, 9.72347163e-006, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       [1.17100705e-004, 6.50846802e-004, 3.02151695e-003, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       [2.13034524e-033, 3.54377968e-031, 4.92391369e-029, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       ...,
       [5.47702336e-017, 1.96767292e-015, 5.90456920e-014, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       [1.11998731e-016, 3.88433680e-015, 1.12524645e-013, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       [7.50859159e-017, 2.65604380e-015, 7.84763828e-014, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115]])

In [11]:
df_atom_features = pkl.load(open('esol_wb97xd_atom_RBF_features.pkl', 'rb'))

In [12]:
df_atom_features

prop0  \
0     [1.1508350519029423e-07, 0.0001171007045049342...   
1     [1.1916961437435905e-07, 0.0001161647242198828...   
2     [2.966889483112151e-14, 9.017544926496134e-12,...   
3     [2.9346255000276062e-05, 2.6372527437554182e-0...   
4     [2.4399349517897947e-07, 2.43930031237325e-07,...   
...                                                 ...   
1035  [1.2063749586372105e-07, 1.4862142330765048e-0...   
1036  [0.000842043186679153, 6.855700444657341e-16, ...   
1037  [3.208381405642046e-05, 3.7848054713998316e-07...   
1038  [3.5583554190725924e-05, 3.03403807863119e-12,...   
1039  [9.312514966129394e-14, 5.408425388792673e-12,...   

                                                  prop1  \
0     [1.1574539451325603e-06, 0.0006508468016923582...   
1     [1.1954139537208336e-06, 0.0006461613369403181...   
2     [7.718260377351683e-13, 1.6985958343188604e-10...   
3     [0.00018632359873296543, 2.0701325829701745e-0...   
4     [2.317818141340951e-06, 2.31726160989295e-06, ...   
...                                                 ...   
1035  [1.209025747539085e-06, 1.223342676121543e-05,...   
1036  [0.003798233250498707, 2.1712657705917565e-14,...   
1037  [0.00020202100314557582, 3.47519084858318e-06,...   
1038  [0.00022189927666219837, 6.093540882699965e-11...   
1039  [2.276841111328368e-12, 1.0500605286374699e-10...   

                                                  prop2  \
0     [9.723471626882657e-06, 0.0030215169538398163,...   
1     [1.00160872981212e-05, 0.003002165738970265, 4...   
2     [1.6771213019535143e-11, 2.6725066091790893e-0...   
3     [0.0009881207829116098, 0.00013572866030460274...   
4     [1.8391089607355458e-05, 1.8387041458917644e-0...   
...                                                 ...   
1035  [1.0120821818909175e-05, 8.410887609145944e-05...   
1036  [0.014310535647195958, 5.743824105195971e-13, ...   
1037  [0.0010625125026871162, 2.6652671725856404e-05...   
1038  [0.0011558179685564674, 1.0222224734672866e-09...   
1039  [4.6497056281602907e-11, 1.7028830320225992e-0...   

                                                  prop3  \
0     [6.82285240057185e-05, 0.011716510581582497, 5...   
1     [7.009787853593315e-05, 0.011650789444640918, ...   
2     [3.0439430166738104e-10, 3.512161795173147e-08...   
3     [0.004377026712893251, 0.0007433133915866392, ...   
4     [0.00012188845056676852, 0.0001218640583886967...   
...                                                 ...   
1035  [7.076573169820626e-05, 0.00048301712258937916...   
1036  [0.045035723236472223, 1.2691596936499023e-11,...   
1037  [0.0046676530617292674, 0.00017073786002349254...   
1038  [0.005028633570309366, 1.4323465730003497e-08,...   
1039  [7.931314769618256e-10, 2.306653153975617e-08,...   

                                                  prop4  \
0     [0.0003998872842265563, 0.03794884269556179, 5...   
1     [0.00040976856724316734, 0.03776617803859523, ...   
2     [4.614615858734551e-09, 3.855291618429787e-07,...   
3     [0.016194791224816023, 0.003400159930785389, 6...   
4     [0.0006747527225914089, 0.0006746311843328996,...   
...                                                 ...   
1035  [0.0004132922078998275, 0.002316915614282331, ...   
1036  [0.1183819219474693, 2.3423856766322495e-10, 2...   
1037  [0.017127346368507854, 0.000913578584610521, 3...   
1038  [0.01827416458785993, 1.6764005522818395e-07, ...   
1039  [1.1300350306751861e-08, 2.6097972330946243e-0...   

                                                  prop5  \
0     [0.0019576552165228894, 0.10266579539642781, 4...   
1     [0.002000780293463717, 0.1022533892634484, 4.1...   
2     [5.84334574275946e-08, 3.5348170989384325e-06,...   
3     [0.0500493571340572, 0.01299133333993685, 3.01...   
4     [0.0031199937788810583, 0.003119494186547116, ...   
...                                                 ...   
1035  [0.002016129509526116, 0.009282926238688033, 0...   
1036  [0.25992055445591733, 3.611

In [23]:
loaded[7]

array([[2.55145405e-004, 1.30985746e-003, 5.61677873e-003, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       [1.90049994e-018, 8.02235393e-017, 2.82854289e-015, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       [3.69512701e-008, 4.04123296e-007, 3.69169145e-006, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       [2.03092857e-017, 7.65751884e-016, 2.41161786e-014, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       [2.03092857e-017, 7.65751884e-016, 2.41161786e-014, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       [2.03092857e-017, 7.65751884e-016, 2.41161786e-014, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115]])

In [24]:
loaded[7].shape

(6, 650)

In [48]:
# test mask out extra features
def mask_features_extra(features_extra: np.ndarray, keep_features: List[bool], feature_length: int = 50) -> np.ndarray:
    """
    Masks certain features in features_extra(atom/bond) based on the keep_features boolean vector.

    :param features_extra: A 2D numpy array with shape (num_atoms or num_bonds, feature_vector) where feature_vector is a multiple of feature_length.
    :param keep_features: A boolean vector indicating which features to keep.
    :return: A masked 2D numpy array with the same shape as features_extra.
    """
    _, feature_vector = features_extra.shape
    num_features = feature_vector // feature_length  # Each feature has length 50

    if len(keep_features) != num_features:
        raise ValueError("Length of keep_features does not match the number of features in features_extra.")

    # Create a mask to apply to features_extra
    mask = np.ones_like(features_extra)

    for i, keep in enumerate(keep_features):
        if not keep:
            mask[:, i*50:(i+1)*50] = 0

    # Apply the mask to features_extra
    masked_features = features_extra * mask

    return masked_features

In [49]:
mask_features_extra(loaded[7], [True]*13)

array([[2.55145405e-004, 1.30985746e-003, 5.61677873e-003, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       [1.90049994e-018, 8.02235393e-017, 2.82854289e-015, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       [3.69512701e-008, 4.04123296e-007, 3.69169145e-006, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       [2.03092857e-017, 7.65751884e-016, 2.41161786e-014, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       [2.03092857e-017, 7.65751884e-016, 2.41161786e-014, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       [2.03092857e-017, 7.65751884e-016, 2.41161786e-014, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115]])

In [50]:
(mask_features_extra(loaded[7], [True]*13) == loaded[7]).all()

True

In [51]:
(mask_features_extra(loaded[7], [False]*13)).any()

False

In [52]:
maksed_extra_atom_feat = mask_features_extra(loaded[7], [False] + [True]*12)

In [53]:
maksed_extra_atom_feat

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        2.95654057e-106, 8.55867443e-111, 1.98831132e-115]])

In [54]:
maksed_extra_atom_feat.shape

(6, 650)

In [37]:
maksed_extra_atom_feat[0]

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 3.60514357e-004, 1.78456824e-003,
       7.37854527e-003, 2

In [38]:
maksed_extra_atom_feat[1]

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 1.07892297e-024, 8.50469361e-023,
       5.59955995e-021, 3

In [39]:
maksed_extra_atom_feat = mask_atom_features_extra(loaded[7], [True] + [False] + [True]*11)

In [40]:
maksed_extra_atom_feat[0]

array([2.55145405e-004, 1.30985746e-003, 5.61677873e-003, 2.01176657e-002,
       6.01859128e-002, 1.50396978e-001, 3.13913766e-001, 5.47278777e-001,
       7.96955082e-001, 9.69362190e-001, 9.84839141e-001, 8.35740634e-001,
       5.92385923e-001, 3.50723554e-001, 1.73441145e-001, 7.16417725e-002,
       2.47176687e-002, 7.12320895e-003, 1.71463172e-003, 3.44741065e-004,
       5.78951490e-005, 8.12116485e-006, 9.51527775e-007, 9.31218525e-008,
       7.61217453e-009, 5.19748040e-010, 2.96417593e-011, 1.41202403e-012,
       5.61832930e-014, 1.86723632e-015, 5.18344359e-017, 1.20188927e-018,
       2.32775643e-020, 3.76562965e-022, 5.08820579e-024, 5.74273431e-026,
       5.41376965e-028, 4.26292622e-030, 2.80377302e-032, 1.54029846e-034,
       7.06795707e-037, 2.70900570e-039, 8.67267212e-042, 2.31911844e-044,
       5.17988270e-047, 9.66371055e-050, 1.50589571e-052, 1.96007582e-055,
       2.13097247e-058, 1.93512846e-061, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0

In [41]:
maksed_extra_atom_feat[1]

array([1.90049994e-018, 8.02235393e-017, 2.82854289e-015, 8.33010955e-014,
       2.04911178e-012, 4.21024705e-011, 7.22564306e-010, 1.03579169e-008,
       1.24021029e-007, 1.24035281e-006, 1.03614881e-005, 7.22979564e-005,
       4.21363492e-004, 2.05123199e-003, 8.34064528e-003, 2.83277130e-002,
       8.03619322e-002, 1.90421604e-001, 3.76885182e-001, 6.23058606e-001,
       8.60351120e-001, 9.92314987e-001, 9.55983434e-001, 7.69268901e-001,
       5.17050519e-001, 2.90278435e-001, 1.36120508e-001, 5.33162192e-002,
       1.74430377e-002, 4.76663490e-003, 1.08799939e-003, 2.07430400e-004,
       3.30326301e-005, 4.39380618e-006, 4.88163867e-007, 4.53019982e-008,
       3.51152755e-009, 2.27353579e-010, 1.22951690e-011, 5.55385074e-013,
       2.09546735e-014, 6.60381025e-016, 1.73834218e-017, 3.82210788e-019,
       7.01936149e-021, 1.07676088e-022, 1.37964682e-024, 1.47653440e-026,
       1.31991575e-028, 9.85543607e-031, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0

In [13]:
df_atom_features.iloc[[7]]

prop0  \
7  [0.00025514540490579013, 1.9004999429873e-18, ...   

                                               prop1  \
7  [0.0013098574558733295, 8.022353931279541e-17,...   

                                               prop2  \
7  [0.005616778725069181, 2.8285428935806297e-15,...   

                                               prop3  \
7  [0.02011766568728541, 8.330109550994726e-14, 2...   

                                               prop4  \
7  [0.06018591284187158, 2.0491117805627195e-12, ...   

                                               prop5  \
7  [0.1503969781133047, 4.2102470533987155e-11, 0...   

                                               prop6  \
7  [0.31391376642849633, 7.225643064435992e-10, 0...   

                                               prop7  \
7  [0.547278776573014, 1.0357916872207324e-08, 0....   

                                               prop8  \
7  [0.7969550824987442, 1.240210293182113e-07, 0....   

                                               prop9  ...  \
7  [0.9693621898437794, 1.2403528102216066e-06, 0...  ...   

                                             prop640  \
7  [3.665820411179459e-77, 3.665820411179459e-77,...   

                                             prop641  \
7  [4.950024531949458e-81, 4.950024531949458e-81,...   

                                             prop642  \
7  [5.36412304660668e-85, 5.36412304660668e-85, 5...   

                                             prop643  \
7  [4.664932088220713e-89, 4.664932088220713e-89,...   

                                             prop644  \
7  [3.255720648180577e-93, 3.255720648180577e-93,...   

                                             prop645  \
7  [1.8234932332882174e-97, 1.8234932332882174e-9...   

                                             prop646  \
7  [8.196272562643508e-102, 8.196272562643508e-10...   

                                             prop647  \
7  [2.9565405666812316e-106, 2.9565405666812316e-...   

                                             prop648  \
7  [8.558674434153366e-111, 8.558674434153366e-11...   

                                             prop649  
7  [1.9883113175022158e-115, 1.9883113175022158e-...  

[1 rows x 650 columns]

In [14]:
df_atom_features.iloc[[7]].prop0.values

array([array([2.55145405e-04, 1.90049994e-18, 3.69512701e-08, 2.03092857e-17,
              2.03092857e-17, 2.03092857e-17])                               ],
      dtype=object)

In [15]:
df_atom_features.iloc[[7]]

prop0  \
7  [0.00025514540490579013, 1.9004999429873e-18, ...   

                                               prop1  \
7  [0.0013098574558733295, 8.022353931279541e-17,...   

                                               prop2  \
7  [0.005616778725069181, 2.8285428935806297e-15,...   

                                               prop3  \
7  [0.02011766568728541, 8.330109550994726e-14, 2...   

                                               prop4  \
7  [0.06018591284187158, 2.0491117805627195e-12, ...   

                                               prop5  \
7  [0.1503969781133047, 4.2102470533987155e-11, 0...   

                                               prop6  \
7  [0.31391376642849633, 7.225643064435992e-10, 0...   

                                               prop7  \
7  [0.547278776573014, 1.0357916872207324e-08, 0....   

                                               prop8  \
7  [0.7969550824987442, 1.240210293182113e-07, 0....   

                                               prop9  ...  \
7  [0.9693621898437794, 1.2403528102216066e-06, 0...  ...   

                                             prop640  \
7  [3.665820411179459e-77, 3.665820411179459e-77,...   

                                             prop641  \
7  [4.950024531949458e-81, 4.950024531949458e-81,...   

                                             prop642  \
7  [5.36412304660668e-85, 5.36412304660668e-85, 5...   

                                             prop643  \
7  [4.664932088220713e-89, 4.664932088220713e-89,...   

                                             prop644  \
7  [3.255720648180577e-93, 3.255720648180577e-93,...   

                                             prop645  \
7  [1.8234932332882174e-97, 1.8234932332882174e-9...   

                                             prop646  \
7  [8.196272562643508e-102, 8.196272562643508e-10...   

                                             prop647  \
7  [2.9565405666812316e-106, 2.9565405666812316e-...   

                                             prop648  \
7  [8.558674434153366e-111, 8.558674434153366e-11...   

                                             prop649  
7  [1.9883113175022158e-115, 1.9883113175022158e-...  

[1 rows x 650 columns]

In [127]:
df_mol_features = pd.read_csv('esol_wb97xd_molecule_features.csv')

In [128]:
df_mol_features

HOMO-3/LUMO  HOMO-3/LUMO+1  HOMO-3/LUMO+2  HOMO-3/LUMO+3  HOMO-2/LUMO  \
0         0.42287        0.44078        0.49119        0.50135      0.40079   
1         0.43167        0.43484        0.50212        0.50642      0.41025   
2         0.40350        0.40350        0.41296        0.47086      0.40100   
3         0.42213        0.42682        0.47774        0.48758      0.39166   
4         0.45831        0.46568        0.53367        0.55065      0.45204   
...           ...            ...            ...            ...          ...   
1035      0.48417        0.50066        0.54587        0.57138      0.44039   
1036      0.33880        0.40067        0.41020        0.42624      0.33031   
1037      0.55250        0.56835        0.59509        0.60013      0.54729   
1038      0.37690        0.45862        0.46539        0.46979      0.36734   
1039      0.37851        0.41068        0.45218        0.45970      0.36477   

      HOMO-2/LUMO+1  HOMO-2/LUMO+2  HOMO-2/LUMO+3  HOMO-1/LUMO  HOMO-1/LUMO+1  \
0           0.41870        0.46911        0.47927      0.38187        0.39978   
1           0.41342        0.48070        0.48500      0.38053        0.38370   
2           0.40100        0.41046        0.46836      0.36110        0.36110   
3           0.39635        0.44727        0.45711      0.37591        0.38060   
4           0.45941        0.52740        0.54438      0.38491        0.39228   
...             ...            ...            ...          ...            ...   
1035        0.45688        0.50209        0.52760      0.39704        0.41353   
1036        0.39218        0.40171        0.41775      0.30893        0.37080   
1037        0.56314        0.58988        0.59492      0.49062        0.50647   
1038        0.44906        0.45583        0.46023      0.36150        0.44322   
1039        0.39694        0.43844        0.44596      0.34294        0.37511   

      HOMO-1/LUMO+2  HOMO-1/LUMO+3  HOMO/LUMO  HOMO/LUMO+1  HOMO/LUMO+2  \
0           0.45019        0.46035    0.35052      0.36843      0.41884   
1           0.45098        0.45528    0.37559      0.37876      0.44604   
2           0.37056        0.42846    0.36110      0.36110      0.37056   
3           0.43152        0.44136    0.33973      0.34442      0.39534   
4           0.46027        0.47725    0.37640      0.38377      0.45176   
...             ...            ...        ...          ...          ...   
1035        0.45874        0.48425    0.33460      0.35109      0.39630   
1036        0.38033        0.39637    0.30052      0.36239      0.37192   
1037        0.53321        0.53825    0.48952      0.50537      0.53211   
1038        0.44999        0.45439    0.33716      0.41888      0.42565   
1039        0.41661        0.42413    0.30535      0.33752      0.37902   

      HOMO/LUMO+3        IP        EA  mulliken_dipole_tot  \
0         0.42900  0.284930 -0.064603               1.6834   
1         0.45034  0.308448 -0.068981               2.1784   
2         0.42846  0.342901 -0.020171               0.0002   
3         0.40518  0.305503 -0.036540               3.9417   
4         0.46874  0.314013 -0.068165               0.6561   
...           ...       ...       ...                  ...   
1035      0.42181  0.261887 -0.078499               2.1405   
1036      0.38796  0.298985  0.000953               5.4654   
1037      0.53715  0.393640 -0.129782               1.9768   
1038      0.43005  0.321706 -0.017889               4.9490   
1039      0.38654  0.299168 -0.010051               1.6873   

      mulliken_quadrupoles  
0                13.621000  
1                11.904446  
2                 2.852600  
3                 3.436641  
4                 3.976662  
...                    ...  
1035              6.450940  
1036             14.688364  
1037              0.702359  
1038             19.273329  
1039              8.661068  

[1040 rows x 20 columns]

In [129]:
df_mol_features.iloc[[7]]

HOMO-3/LUMO  HOMO-3/LUMO+1  HOMO-3/LUMO+2  HOMO-3/LUMO+3  HOMO-2/LUMO  \
7      0.67249         0.6725        0.68771        0.76879      0.56122   

   HOMO-2/LUMO+1  HOMO-2/LUMO+2  HOMO-2/LUMO+3  HOMO-1/LUMO  HOMO-1/LUMO+1  \
7        0.56123        0.57644        0.65752      0.53228        0.53229   

   HOMO-1/LUMO+2  HOMO-1/LUMO+3  HOMO/LUMO  HOMO/LUMO+1  HOMO/LUMO+2  \
7         0.5475        0.62858    0.53228      0.53229       0.5475   

   HOMO/LUMO+3        IP       EA  mulliken_dipole_tot  mulliken_quadrupoles  
7      0.62858  0.453058 -0.13823               3.8165                 2.179

In [130]:
example = dict()
example['smiles'] = df_smi.iloc[[7]].smiles.values[0]
example['target'] = df_smi.iloc[[7]].logSolubility.values[0]
example['atom_qm_features'] = df_atom_features.iloc[[7]].values[0]
example['bond_qm_features'] = df_bond_features.iloc[[7]].values[0]
example['mol_qm_features'] = df_mol_features.iloc[[7]].values[0]

In [131]:
example.keys()

dict_keys(['smiles', 'target', 'atom_qm_features', 'bond_qm_features', 'mol_qm_features'])

In [132]:
with open('example_mol.pkl', 'wb') as f:
    pkl.dump(example, f)

# load a test model

In [1]:
import sys
sys.path.insert(0, '/home/oscarwu/code/chemprop_developing')
from chemprop.models.model import MoleculeModel
from pprint import pprint

In [5]:
import torch
from chemprop.utils import load_checkpoint, load_scalers
from chemprop.args import TrainArgs
from chemprop.features import set_extra_bond_fdim

In [6]:
path = "/home/oscarwu/code/chemprop_developing/developing/shap_v1/data/model.pt"
state = torch.load(path, map_location=lambda storage, loc: storage)
train_args = TrainArgs()
train_args.from_dict(vars(state["args"]), skip_unsettable=True)
set_extra_bond_fdim(train_args.bond_features_size)
model = load_checkpoint(path)
scalers= load_scalers(path)

Loading pretrained parameter "encoder.encoder.0.cached_zero_vector".
Loading pretrained parameter "encoder.encoder.0.W_i.weight".
Loading pretrained parameter "encoder.encoder.0.W_h.weight".
Loading pretrained parameter "encoder.encoder.0.W_o.weight".
Loading pretrained parameter "encoder.encoder.0.W_o.bias".
Loading pretrained parameter "encoder.encoder.0.atom_descriptors_layer.weight".
Loading pretrained parameter "encoder.encoder.0.atom_descriptors_layer.bias".
Loading pretrained parameter "readout.1.weight".
Loading pretrained parameter "readout.1.bias".
Loading pretrained parameter "readout.4.weight".
Loading pretrained parameter "readout.4.bias".
Loading pretrained parameter "readout.7.weight".
Loading pretrained parameter "readout.7.bias".


In [4]:
model

MoleculeModel(
  (encoder): MPN(
    (encoder): ModuleList(
      (0): MPNEncoder(
        (dropout): Dropout(p=0.1, inplace=False)
        (act_func): ReLU()
        (W_i): Linear(in_features=347, out_features=1000, bias=False)
        (W_h): Linear(in_features=1000, out_features=1000, bias=False)
        (W_o): Linear(in_features=1133, out_features=1000, bias=True)
        (atom_descriptors_layer): Linear(in_features=1650, out_features=1650, bias=True)
      )
    )
  )
  (readout): Sequential(
    (0): Dropout(p=0.1, inplace=False)
    (1): Linear(in_features=1670, out_features=1650, bias=True)
    (2): ReLU()
    (3): Dropout(p=0.1, inplace=False)
    (4): Linear(in_features=1650, out_features=1650, bias=True)
    (5): ReLU()
    (6): Dropout(p=0.1, inplace=False)
    (7): Linear(in_features=1650, out_features=1, bias=True)
  )
)

In [7]:
scalers

(<chemprop.data.scaler.StandardScaler at 0x7efeeac7c160>,
 None,
 None,
 None)

In [8]:
target_scaler, mol_feature_scaler, _, _, _ = scalers

In [9]:
mol_feature_scaler